# Generated by Django 4.1.7 on 2024-10-31 07:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_deposite_options_alter_deposite_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposite',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 31, 7, 42, 45, 993398), null=True),
        ),
        migrations.AlterField(
            model_name='deposite',
            name='expire_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 31, 8, 42, 45, 993398), null=True),
        ),
    ]
