# Generated by Django 4.1.7 on 2025-05-27 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_deposite_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_deposite',
        ),
        migrations.AddField(
            model_name='user',
            name='user_deposit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
