# Generated by Django 4.1.7 on 2025-05-27 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_remove_user_user_deposite_user_user_deposit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_deposit',
            new_name='user_deposite',
        ),
    ]
