# Generated by Django 4.1.7 on 2025-05-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_rename_user_deposit_user_user_deposite'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ban',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
