# Generated by Django 4.1.7 on 2023-07-22 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trader',
            name='loss',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='trader',
            name='win',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
